"""add uuid default

Revision ID: 16ba74805a36
Revises: 05e14883dab3
Create Date: 2026-02-03 15:08:39.380560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16ba74805a36'
down_revision: Union[str, Sequence[str], None] = '05e14883dab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'uuid',
        server_default=sa.text('gen_random_uuid()')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'uuid',
        server_default=None
    )
    # ### end Alembic commands ###
