"""init schema

Revision ID: b5abc414d963
Revises: 
Create Date: 2026-02-02 20:31:22.692330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5abc414d963'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_employee_access')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_table('user_employee_access',
    sa.Column('uuid_user', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('uuid_employee', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('access_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['uuid_employee'], ['employees.uuid'], name=op.f('user_employee_access_uuid_employee_fkey')),
    sa.ForeignKeyConstraint(['uuid_user'], ['users.uuid'], name=op.f('user_employee_access_uuid_user_fkey')),
    sa.PrimaryKeyConstraint('uuid_user', 'uuid_employee', name=op.f('user_employee_access_pkey'))
    )
    # ### end Alembic commands ###
